# Generated by Django 2.1.7 on 2019-04-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=4)),
                ('course_num', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('corequisites', models.TextField(blank=True, null=True)),
                ('min_credits', models.FloatField()),
                ('max_credits', models.FloatField()),
                ('distribution_of_hours', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.IntegerField()),
                ('B', models.IntegerField()),
                ('C', models.IntegerField()),
                ('D', models.IntegerField()),
                ('F', models.IntegerField()),
                ('I', models.IntegerField()),
                ('S', models.IntegerField()),
                ('U', models.IntegerField()),
                ('Q', models.IntegerField()),
                ('X', models.IntegerField()),
                ('gpa', models.FloatField()),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_days', models.CharField(max_length=7)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('meeting_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('term_code', models.IntegerField()),
                ('crn', models.IntegerField()),
                ('dept', models.CharField(max_length=5)),
                ('course_num', models.CharField(max_length=6)),
                ('section_num', models.CharField(max_length=6)),
                ('min_credits', models.FloatField(null=True)),
                ('max_credits', models.FloatField(null=True)),
                ('instructor', models.CharField(blank=True, max_length=150, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Course')),
                ('meetings', models.ManyToManyField(to='scraper.Meeting')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.AddField(
            model_name='grades',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='scraper.Section'),
        ),
    ]
