# Generated by Django 2.1.7 on 2019-03-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='instructor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
