# Generated by Django 2.1.7 on 2019-03-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20190330_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
