# Generated by Django 2.1.7 on 2019-03-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20190330_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='max_credits',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='min_credits',
            field=models.FloatField(null=True),
        ),
    ]
