# Generated by Django 2.1.7 on 2019-03-31 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20190330_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.IntegerField()),
                ('B', models.IntegerField()),
                ('C', models.IntegerField()),
                ('D', models.IntegerField()),
                ('F', models.IntegerField()),
                ('I', models.IntegerField()),
                ('S', models.IntegerField()),
                ('U', models.IntegerField()),
                ('Q', models.IntegerField()),
                ('X', models.IntegerField()),
                ('gpa', models.FloatField()),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='scraper.Section')),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.RemoveField(
            model_name='grade',
            name='section',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
