version: "3.1"

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER_FILE=/run/secrets/SECRET_POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/SECRET_POSTGRES_PASS
      - POSTGRES_DB=goodbullschedules
    secrets:
      - SECRET_POSTGRES_USER
      - SECRET_POSTGRES_PASS
  redis:
    image: redis:latest
  elasticsearch:
    image: elasticsearch:6.5.0
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  web:
    build: .
    command: python manage.py runserver --settings=goodbullschedules.settings.docker 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - elasticsearch
    container_name: good-bull-schedules
    secrets:
      - SECRET_DJANGO_KEY
      - SECRET_POSTGRES_USER
      - SECRET_POSTGRES_PASS

volumes:
  pgdata:
  esdata:

secrets:
  SECRET_DJANGO_KEY:
    file: ./config/django_key
  SECRET_POSTGRES_USER:
    file: ./config/postgres_username
  SECRET_POSTGRES_PASS:
    file: ./config/postgres_password
